### ISSUE TITLE
populate DB with basic data on setup of a new instance

### ISSUE THREAD

**Issue by hucki** [AlexKMarshall/regMan#13]
populate DB with basic data on setup of a new instance
https://sequelize.org/master/manual/migrations.html

- [x] create DB and tables with `sequelize-cli db:migrate`
- [x] seed DB with with `sequelize-cli db:migrate` (instrumentCategories (Register Form not usable without))

**Comment by AlexKMarshall** [comment]
In the GroupsDisplay.js component, which displays the charts, there are a lot of hardcoded instrument names. I haven't worked out how they're all used yet, but I suspect this needs to be considered when creating instrument data.

Though ultimately this shouldn't be hardcoded in the component this way.
